### ISSUE TITLE
Deprecation notice for Gacela\Framework\AbstractDependencyProvider

### ISSUE THREAD

**Issue by jasalt** [phel-lang/web-skeleton#4]
Following readme I ran `composer run:dev` and get following notice on top of page:

```[2024-08-18T14:39:20+00:00] Error Unknown(4437) found! message: "Since gacela-project/gacela 1.8: `Gacela\Framework\AbstractDependencyProvider` is deprecated and will be removed in version 2.0. Use `Gacela\Framework\AbstractProvider` instead. Where? Check your module `Command`" file: /home/user/dev/phel-test/example-app/vendor/symfony/deprecation-contracts/function.php:25 context: {"errno":16384} [2024-08-18T14:39:20+00:00] Error Unknown(4437) found! message: "Since gacela-project/gacela 1.8: `Gacela\Framework\AbstractDependencyProvider` is deprecated and will be removed in version 2.0. Use `Gacela\Framework\AbstractProvider` instead. Where? Check your module `Build`" file: /home/user/dev/phel-test/example-app/vendor/symfony/deprecation-contracts/function.php:25 context: {"errno":16384} [2024-08-18T14:39:20+00:00] Error Unknown(4437) found! message: "Since gacela-project/gacela 1.8: `Gacela\Framework\AbstractDependencyProvider` is deprecated and will be removed in version 2.0. Use `Gacela\Framework\AbstractProvider` instead. Where? Check your module `Compiler`" file: /home/user/dev/phel-test/example-app/vendor/symfony/deprecation-contracts/function.php:25 context: {"errno":16384} ```

Otherwise seems to work ok. PHP 8.2.20 running locally on Debian 12.

**Comment by Chemaclass** [comment]
Yeah, this is a deprecation notice by gacela 1.8 that I released yesterday. I plan to upgrade this project (and others) to dismiss this message. Thanks for the reminder

**Comment by Chemaclass** [comment]
@jasalt please try again. I released a new minor version for phel with some fixes and upgrading gacela to get rid of the warning that you shared https://github.com/phel-lang/phel-lang/releases/tag/v0.15.2 
If you get another error, try removing the cache (`data/.cache/gacela-*`). 
> You can safely remove these files. They are autogenerated by gacela to speed up the class resolver. They might be pointing to the old files, that might be a cause for error.

![Screenshot 2024-08-19 at 21 02 05](https://github.com/user-attachments/assets/054ffa40-368d-4175-8e60-bad3c0b2eef8)

**Comment by jasalt** [comment]
Great, it works. With another project https://github.com/jasalt/phel-wp-plugin, I had also another error after `composer update`:

```
PHP Fatal error:  Uncaught TypeError: Gacela\Framework\ClassResolver\AbstractClassResolver::createInstance(): Return value must be of type object, null returned in /srv/www/wordpress-one/public_html/wp-content/pl
ugins/phel-wp-plugin/vendor/gacela-project/gacela/src/Framework/ClassResolver/AbstractClassResolver.php:151
```

This was fixed by removing the cached files.
